### ISSUE TITLE
[Error] HTTPConnectionPool(host='localhost', port=48063): Read timed out. (read timeout=120)

### ISSUE THREAD

**Issue by EstherCho-7** [DE32FinalTeam2/FinalRepo#6]
## 크롤링 도중 어느 정도의 시간이 지나면 아래와 같은 에러 발생
![image](https://github.com/user-attachments/assets/cc11577a-cc11-40b9-8515-3135db0e9c9b)

- 크롤링하는 데이터의 개수는 약 1100개 정도
- 더 많은 데이터 수를 크롤링 시 어떻게 해결해야 하는지 의문
- 여러 번의 크롤링 시도를 했으나 비슷한 양상으로 종료됨

**Comment by DONGUK777** [comment]
## 에러 해결 방법 제안 드립니다.
1. 크롤링 링크일단 수집했으면 그 링크 리스트에서 천개씩으로 끊어서 진행
2. Mysql 연결 재사용 연결 풀링 설정 코드 추가
```bash
connection_pool = pooling.MySQLConnectionPool(pool_name="<site_name>_pool", pool_size=5, **db_config)
```

**Comment by EstherCho-7** [comment]
## 해결
```python
connection_pool = pooling.MySQLConnectionPool(pool_name="<site_name>_pool", pool_size=5, **db_config)
```
- 해당 코드로 해결 完
